/** Preset skills for projects (and freelancer profiles). Typeahead suggests from this list. */
export const PRESET_SKILLS: string[] = [
  'React',
  'Vue.js',
  'Angular',
  'Node.js',
  'Python',
  'TypeScript',
  'JavaScript',
  'PHP',
  'Laravel',
  'Ruby on Rails',
  'Java',
  'Kotlin',
  'Swift',
  'Flutter',
  'React Native',
  'Next.js',
  'Django',
  'FastAPI',
  'PostgreSQL',
  'MongoDB',
  'AWS',
  'Docker',
  'Kubernetes',
  'REST API',
  'GraphQL',
  'UI/UX Design',
  'Figma',
  'Adobe XD',
  'Web Design',
  'Mobile App Design',
  'Logo Design',
  'Branding',
  'Illustration',
  'Photoshop',
  'Video Editing',
  'Motion Graphics',
  'Content Writing',
  'Copywriting',
  'Technical Writing',
  'SEO',
  'Digital Marketing',
  'Social Media Marketing',
  'Email Marketing',
  'WordPress',
  'Shopify',
  'Data Entry',
  'Excel',
  'Google Sheets',
  'CRM',
  'API Integration',
  'Web Scraping',
  'Machine Learning',
  'Data Analysis',
  'Blockchain',
  'Solidity',
  'DevOps',
  'CI/CD',
  'Linux',
  'Git',
];
